
# Task 9: Random Forest – Credit Card Fraud Detection
# Author: Generated by ChatGPT
# Dataset: Kaggle Credit Card Fraud Dataset (creditcard.csv)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler

# =====================
# 1. Load Dataset
# =====================
data = pd.read_csv("creditcard.csv")

print("Dataset Shape:", data.shape)
print("\nClass Distribution:")
print(data['Class'].value_counts())

# =====================
# 2. Separate Features & Target
# =====================
X = data.drop(columns=['Class'])
y = data['Class']

# =====================
# 3. Train-Test Split (Stratified)
# =====================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# =====================
# 4. Baseline Model: Logistic Regression
# =====================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(max_iter=1000, n_jobs=-1)
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print("\nLogistic Regression Performance:")
print(classification_report(y_test, y_pred_lr))

# =====================
# 5. Random Forest Model
# =====================
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("\nRandom Forest Performance:")
print(classification_report(y_test, y_pred_rf))

# =====================
# 6. Metrics Comparison
# =====================
print("Logistic Regression F1 Score:", f1_score(y_test, y_pred_lr))
print("Random Forest F1 Score:", f1_score(y_test, y_pred_rf))

# =====================
# 7. Feature Importance Plot
# =====================
importances = rf.feature_importances_
feature_names = X.columns

feature_imp_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False).head(15)

plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', data=feature_imp_df)
plt.title("Top 15 Feature Importances - Random Forest")
plt.tight_layout()
plt.savefig("feature_importance.png")
plt.show()

# =====================
# 8. Save Model
# =====================
joblib.dump(rf, "random_forest_fraud_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("\nModel and scaler saved successfully!")
